em = ['SKULL', 'ALARM_CLOCK', 'WATERMELON', 'SAFETY_PIN', 'ROLL_OF_PAPER', 'SPOON', 'CUSTARD', 'SPIDER', 'SNAIL',
      'BEER_MUG', 'COFFIN', 'BIRTHDAY_CAKE', 'LOCKED', 'MICROSCOPE', 'TROPHY', 'BOMB', 'LOBSTER', 'PIZZA', 'HAMBURGER',
      'GOAT', 'ROSE', 'BANANA', 'BASEBALL', 'CAMERA', 'DOG', 'MAGNET', 'RAINBOW', 'TOMATO', 'SNOWMAN', 'BONE']
